"""empty message

Revision ID: 436062579b6b
Revises: cdebcafe9f36
Create Date: 2022-08-15 21:07:36.735639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436062579b6b'
down_revision = 'cdebcafe9f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'upcoming')
    # ### end Alembic commands ###
