"""empty message

Revision ID: 67767434c1a4
Revises: b684f304c7ea
Create Date: 2022-08-15 20:19:35.615420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67767434c1a4'
down_revision = 'b684f304c7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_date')
    # ### end Alembic commands ###
