"""empty message

Revision ID: cdebcafe9f36
Revises: 67767434c1a4
Create Date: 2022-08-15 20:48:27.808106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdebcafe9f36'
down_revision = '67767434c1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_date')
    op.add_column('Venue', sa.Column('shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'shows_count')
    op.add_column('Show', sa.Column('show_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
